export const WineTypes = ["Red", "White", "Rose", "Sparkling"];

export const WineType = {
    "RED": "RED",
    "WHITE": "WHITE",
    "ROSE": "ROSE",
    "SPARKLING": "SPARKLING"
};

export const GrapeVarietals = [
    "abouriou",
    "agiorgitiko",
    "aglianico",
    "aleatico",
    "alfrocheiro",
    "alicante bouschet",
    "aragonês",
    "aramon",
    "areni noir",
    "aspiran",
    "băbească neagră",
    "babić",
    "baco noir",
    "baga",
    "barbarossa",
    "barbera",
    "bastardo",
    "black muscat",
    "blauburger",
    "blauburgunder",
    "blauer frühburgunder",
    "blauer spätburgunder",
    "blauer wildbacher",
    "blaufränkisch",
    "bobal",
    "bonarda",
    "brachetto",
    "braquet",
    "breton",
    "brocol",
    "brunello",
    "burgund mare",
    "cabernet",
    "cabernet dorsa",
    "cabernet franc",
    "cabernet gernischt",
    "cabernet sauvignon",
    "cabernet severny",
    "caladoc",
    "callet",
    "canaiolo",
    "cannonau",
    "carcajolo nero",
    "carignan",
    "carmenère",
    "carnelian",
    "castelão",
    "catawba",
    "cencibel",
    "centurian",
    "cesanese",
    "chambourcin",
    "chancellor",
    "charbono",
    "chardonnay",
    "chiavennasca",
    "ciliegiolo",
    "cinsault",
    "colorino",
    "concord",
    "corvina",
    "cot",
    "couderc noir",
    "counoise",
    "criolla chica",
    "crljenak kaštelanski",
    "croatina",
    "delaware",
    "dolcetto",
    "domina",
    "dornfelder",
    "dunkelfelder",
    "durif",
    "espadeiro",
    "evmolpia",
    "fer servadou",
    "fetească neagră",
    "fogoneu",
    "franconia",
    "frankovka",
    "frappato",
    "freisa",
    "frühburgunder",
    "gaglioppo",
    "gamay",
    "gamé",
    "gamza",
    "garnacha",
    "garrut",
    "graciano",
    "grand noir de la calmette",
    "grenache",
    "grignolino",
    "grolleau",
    "groppello",
    "harriague",
    "helfensteiner",
    "heroldrebe",
    "isabella",
    "jaen",
    "joão de santarém",
    "jurançon noir",
    "kadarka",
    "kalecik karasi",
    "kékfrankos",
    "lagrein",
    "lambrusco",
    "lambrusco grasparossa",
    "lemberger",
    "limnio",
    "lledoner pelut",
    "magaratch ruby",
    "magliocco",
    "malbec",
    "malvasia nera",
    "mammolo",
    "mandilaria",
    "manto negro",
    "maratheftiko",
    "maréchal foch",
    "marselan",
    "marzemino",
    "mataro",
    "mavro",
    "mavrodaphne",
    "mavrud",
    "mazuelo",
    "melnik",
    "mencía",
    "merlot",
    "mission",
    "modra frankinja",
    "modri pinot",
    "molinara",
    "monastrell",
    "mondeuse",
    "monica",
    "montepulciano",
    "morellino",
    "moreto",
    "moristel",
    "morrastel",
    "mourisco tinto",
    "mourvèdre",
    "müllerebe",
    "muscardin",
    "muscat hamburg",
    "nebbiolo",
    "negramoll",
    "negrette",
    "negroamaro",
    "nerello cappuccio",
    "nerello mascalese",
    "nero d'avola",
    "nero di troia",
    "nielluccio",
    "norton",
    "öküzgözü",
    "ormeasco",
    "ottavianello",
    "país",
    "pamid",
    "papazkarasi",
    "parraleta",
    "pelaverga",
    "periquita",
    "perricone",
    "petit verdot",
    "petite sirah",
    "piedirosso",
    "pignolo",
    "pineau d'aunis",
    "pinenc",
    "pinot meunier",
    "pinot nero",
    "pinot noir",
    "pinotage",
    "plavac mali",
    "porkupac",
    "portan",
    "portugieser",
    "poulsard",
    "pressac",
    "prieto picudo",
    "primitivo",
    "prugnolo gentile",
    "raboso",
    "ramisco",
    "refosco",
    "rondinella",
    "rondo",
    "rossese",
    "rouchet",
    "royalty",
    "rubin",
    "rubired",
    "ruby cabernet",
    "ruen",
    "rufete",
    "sagrantino",
    "salvador",
    "samsó",
    "samtrot",
    "sangiovese",
    "saperavi",
    "saugvignon blanc",
    "schiava",
    "schioppettino",
    "schwarzriesling",
    "sciaccarello",
    "segalin",
    "seibel",
    "shiraz",
    "sousão",
    "spanna",
    "spätburgunder",
    "st laurent",
    "syrah",
    "taminga",
    "tannat",
    "tarrango",
    "tempranillo",
    "teran",
    "teroldego",
    "tibouren",
    "tinta amarela",
    "tinta barroca",
    "tinta cão",
    "tinta miúda",
    "tinta negra",
    "tinta pinheira",
    "tinta roriz",
    "tintilia",
    "tinto fino",
    "touriga franca",
    "touriga nacional",
    "tribidrag",
    "trincadeira",
    "trollinger",
    "trousseau",
    "ull de llebre",
    "uva rara",
    "vaccarèse",
    "valdiguié",
    "vavrinecke",
    "vernatsch",
    "vespolina",
    "villard noir",
    "viognier",
    "vranac",
    "xynomavro",
    "zinfandel",
    "zweigelt",
    "airén",
    "albalonga",
    "albana",
    "albariño",
    "albillo",
    "aligoté",
    "altesse",
    "alvarinho",
    "amigne",
    "ansonica",
    "antão vaz",
    "arinto",
    "arneis",
    "arrufiac",
    "assyrtiko",
    "auxerrois",
    "avesso",
    "azal",
    "bacchus",
    "baco blanc",
    "baiyu",
    "baroque",
    "bergeron",
    "bical",
    "boal",
    "bombino bianco",
    "borrado das moscas",
    "bourboulenc",
    "bouvier",
    "carignan blanc",
    "carignan gris",
    "carricante",
    "catarratto",
    "cayetana blanca",
    "cayuga white",
    "cerceal",
    "cereza",
    "chardonel",
    "chardonnay",
    "chasan",
    "chasselas",
    "chenin blanc",
    "chevrier",
    "clairette",
    "côdega de larinho",
    "colombard",
    "completer",
    "cortese",
    "criolla grande",
    "crouchen",
    "debina",
    "dimiat",
    "dinka",
    "drupeggio",
    "ehrenfelser",
    "elbling",
    "emerald riesling",
    "emir",
    "encruzado",
    "erbaluce",
    "esgana",
    "ezerjó",
    "faber",
    "falanghina",
    "favorita",
    "fendant",
    "fernão pires",
    "fetească alba",
    "fetească regală",
    "fiano",
    "fié gris",
    "flora",
    "folle blanche",
    "friulano",
    "frühroter veltliner",
    "furmint",
    "garganega",
    "garnacha blanca",
    "gewurztraminer",
    "glera",
    "godello",
    "goldberger",
    "gordo",
    "gouais blanc",
    "gouveio",
    "grasă",
    "graševina",
    "grauburgunder",
    "grecanico",
    "grechetto",
    "greco",
    "grenache blanc",
    "grillo",
    "grolleau gris",
    "gros manseng",
    "gros plant",
    "grüner veltliner",
    "gutedel",
    "gutenborner",
    "hanepoot",
    "hárslevelű",
    "heida",
    "humagne",
    "huxelrebe",
    "inzolia",
    "irsai olivér",
    "italian riesling",
    "jacquère",
    "jaén blanca",
    "johannisberg",
    "juhfark",
    "kéknyelü",
    "kerner",
    "királeányka",
    "klevner",
    "koshu",
    "laški rizling",
    "len de l'el",
    "lexia",
    "listan",
    "loureiro",
    "macabeo",
    "malagousia",
    "malvasia",
    "malvazija istarska",
    "malvoisie",
    "maria gomes",
    "marmajuelo",
    "marsanne",
    "mauzac",
    "melon de bourgogne",
    "menu pineau",
    "merseguera",
    "minutolo",
    "misket",
    "molette",
    "mondeuse blanche",
    "morava",
    "morillon",
    "morio-muskat",
    "moscatel",
    "moscato",
    "moschofilero",
    "mtsvane",
    "müller-thurgau",
    "muscadelle",
    "muscat",
    "muskateller",
    "muskotály",
    "narince",
    "neuburger",
    "niagara",
    "nosiola",
    "nuragus",
    "olaszrizling",
    "ondenc",
    "optima",
    "orémus",
    "ortega",
    "palomino",
    "pansa blanca",
    "pardina",
    "parellada",
    "pecorino",
    "pedernã",
    "pedro ximénez",
    "perle",
    "petit courbu",
    "petit manseng",
    "petite arvine",
    "picolit",
    "pigato",
    "pinot beurot",
    "pinot blanc",
    "pinot grigio",
    "pinot gris",
    "piquepoul",
    "prosecco",
    "rabigato",
    "ranina",
    "räuschling",
    "rebula",
    "regner",
    "reichensteiner",
    "rhine riesling",
    "rhoditis",
    "ribolla gialla",
    "rieslaner",
    "riesling",
    "riesling italico",
    "rivaner",
    "rizling",
    "rkatsiteli",
    "robola",
    "rolle",
    "rollo",
    "romorantin",
    "roter veltliner",
    "rotgipfler",
    "roupeiro",
    "roussanne",
    "roussette",
    "ruländer",
    "sacy",
    "sämling 88",
    "sauvignon blanc",
    "sauvignon gris",
    "sauvignon vert",
    "savagnin",
    "savatiano",
    "scheurebe",
    "schönburger",
    "scuppernong",
    "semillon",
    "sercial",
    "seyval blanc",
    "siegerrebe",
    "silvaner",
    "sipon",
    "síria",
    "smederevka",
    "sultana",
    "sylvaner",
    "szürkebarát",
    "talia",
    "tămâioasă românească",
    "tamianka",
    "tamyanka",
    "terret gris",
    "timorasso",
    "tokay d'alsace",
    "torbato",
    "torrontés",
    "trajadura",
    "traminer",
    "trebbiano",
    "treixadura",
    "tresallier",
    "ugni blanc",
    "verdejo",
    "verdelho",
    "verdello",
    "verdicchio",
    "verduzzo",
    "vermentino",
    "vernaccia",
    "vespaiola",
    "vidal",
    "vilana",
    "villard blanc",
    "viognier",
    "viosinho",
    "viura",
    "weissburgunder",
    "weisser riesling",
    "welschriesling",
    "xarel-lo",
    "xynesteri",
    "zalema",
    "zibibbo",
    "zierfandler",
    "zilavka"
];
