"""empty message

Revision ID: 1e640ea33a4d
Revises: ee55f483a4e0
Create Date: 2016-08-01 23:18:42.212220

"""

# revision identifiers, used by Alembic.
revision = '1e640ea33a4d'
down_revision = 'ee55f483a4e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('winery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('formatted_address', sa.String(), nullable=False),
    sa.Column('lat', sa.Numeric(), nullable=False),
    sa.Column('lon', sa.Numeric(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_winery_name'), 'winery', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_winery_name'), table_name='winery')
    op.drop_table('winery')
    ### end Alembic commands ###
