"""empty message

Revision ID: 226d54152e8a
Revises: None
Create Date: 2016-03-13 19:58:55.359600

"""

# revision identifiers, used by Alembic.
revision = '226d54152e8a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=40), nullable=False),
    sa.Column('region', sa.String(length=70), nullable=False),
    sa.Column('subregion', sa.String(length=70), nullable=True),
    sa.Column('vintage', sa.String(length=20), nullable=False),
    sa.Column('varietal', sa.String(length=300), nullable=False),
    sa.Column('production', sa.String(length=300), nullable=False),
    sa.Column('alcohol', sa.String(length=20), nullable=False),
    sa.Column('oak', sa.String(length=70), nullable=False),
    sa.Column('soil', sa.String(length=70), nullable=False),
    sa.Column('farming', sa.String(length=70), nullable=False),
    sa.Column('wine_type', sa.String(length=20), nullable=False),
    sa.Column('fruit_rating', sa.Integer(), nullable=False),
    sa.Column('earth_rating', sa.Integer(), nullable=False),
    sa.Column('body_rating', sa.Integer(), nullable=False),
    sa.Column('tannin_rating', sa.Integer(), nullable=False),
    sa.Column('acid_rating', sa.Integer(), nullable=False),
    sa.Column('alcohol_rating', sa.Integer(), nullable=False),
    sa.Column('main_image_url', sa.String(length=500), nullable=False),
    sa.Column('alt_image_url', sa.String(length=500), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wine_acid_rating'), 'wine', ['acid_rating'], unique=False)
    op.create_index(op.f('ix_wine_alcohol_rating'), 'wine', ['alcohol_rating'], unique=False)
    op.create_index(op.f('ix_wine_body_rating'), 'wine', ['body_rating'], unique=False)
    op.create_index(op.f('ix_wine_country'), 'wine', ['country'], unique=False)
    op.create_index(op.f('ix_wine_earth_rating'), 'wine', ['earth_rating'], unique=False)
    op.create_index(op.f('ix_wine_fruit_rating'), 'wine', ['fruit_rating'], unique=False)
    op.create_index(op.f('ix_wine_name'), 'wine', ['name'], unique=False)
    op.create_index(op.f('ix_wine_region'), 'wine', ['region'], unique=False)
    op.create_index(op.f('ix_wine_tannin_rating'), 'wine', ['tannin_rating'], unique=False)
    op.create_index(op.f('ix_wine_varietal'), 'wine', ['varietal'], unique=False)
    op.create_index(op.f('ix_wine_vintage'), 'wine', ['vintage'], unique=False)
    op.create_index(op.f('ix_wine_wine_type'), 'wine', ['wine_type'], unique=False)
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wine_id', sa.Integer(), nullable=True),
    sa.Column('quote', sa.String(length=500), nullable=False),
    sa.Column('lead', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['wine_id'], ['wine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry')
    op.drop_index(op.f('ix_wine_wine_type'), table_name='wine')
    op.drop_index(op.f('ix_wine_vintage'), table_name='wine')
    op.drop_index(op.f('ix_wine_varietal'), table_name='wine')
    op.drop_index(op.f('ix_wine_tannin_rating'), table_name='wine')
    op.drop_index(op.f('ix_wine_region'), table_name='wine')
    op.drop_index(op.f('ix_wine_name'), table_name='wine')
    op.drop_index(op.f('ix_wine_fruit_rating'), table_name='wine')
    op.drop_index(op.f('ix_wine_earth_rating'), table_name='wine')
    op.drop_index(op.f('ix_wine_country'), table_name='wine')
    op.drop_index(op.f('ix_wine_body_rating'), table_name='wine')
    op.drop_index(op.f('ix_wine_alcohol_rating'), table_name='wine')
    op.drop_index(op.f('ix_wine_acid_rating'), table_name='wine')
    op.drop_table('wine')
    ### end Alembic commands ###
