"""empty message

Revision ID: 93229cb09a87
Revises: 226d54152e8a
Create Date: 2016-03-13 20:37:35.110146

"""

# revision identifiers, used by Alembic.
revision = '93229cb09a87'
down_revision = '226d54152e8a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wine', 'main_image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wine', 'main_image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    ### end Alembic commands ###
