"""empty message

Revision ID: e0e6c4b2e673
Revises: ee55f483a4e0
Create Date: 2016-08-24 23:40:57.663897

"""

# revision identifiers, used by Alembic.
revision = 'e0e6c4b2e673'
down_revision = 'ee55f483a4e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('winery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('formatted_address', sa.String(), nullable=False),
    sa.Column('lat', sa.Numeric(), nullable=False),
    sa.Column('lon', sa.Numeric(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_winery_name'), 'winery', ['name'], unique=False)
    op.add_column(u'wine', sa.Column('winery_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wine', 'winery', ['winery_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wine', type_='foreignkey')
    op.drop_column(u'wine', 'winery_id')
    op.drop_index(op.f('ix_winery_name'), table_name='winery')
    op.drop_table('winery')
    ### end Alembic commands ###
