export enum ActionType {
  REQUEST_WINES,
  RECEIVE_WINES_SUCCESS,
  RECEIVE_WINES_ERROR,
  REQUEST_ENTRY,
  RECEIVE_ENTRY_SUCCESS,
  RECEIVE_ENTRY_ERROR,
  CHANGE_FILTER,
  CLEAR_FILTER,
  TOGGLE_FILTER,
  SELECT_WINE,
}
